# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DODRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DODId', models.CharField(max_length=128)),
                ('Name', models.TextField()),
                ('IsSynonym', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark2CureAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentId', models.IntegerField()),
                ('AnnotationId', models.IntegerField()),
                ('AnnotationText', models.CharField(max_length=512)),
                ('Stage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mark2CurePassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentId', models.IntegerField()),
                ('PassageId', models.IntegerField()),
                ('PassageText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchExplanationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnotationDocumentId', models.IntegerField()),
                ('AnnotationId', models.IntegerField()),
                ('OntologyName', models.CharField(max_length=128, null=True)),
                ('OntologyRecordId', models.IntegerField(null=True)),
                ('MatchExplanation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchStrengthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnotationDocumentId', models.IntegerField()),
                ('AnnotationId', models.IntegerField()),
                ('OntologyName', models.CharField(max_length=128, null=True)),
                ('OntologyRecordId', models.IntegerField(null=True)),
                ('MatchStrength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeshRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeshId', models.CharField(max_length=10)),
                ('Name', models.TextField()),
                ('IsSynonym', models.BooleanField()),
                ('ParentMeshId', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mark2cureannotation',
            name='Passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Mark2CurePassage'),
        ),
    ]
