# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshrecord',
            name='ParentMeshId',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
