# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyMatchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GeneratedOn', models.DateField()),
                ('OntologyName', models.CharField(max_length=128)),
                ('OntologyRecordId', models.IntegerField()),
                ('Annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Mark2CureAnnotation')),
            ],
        ),
    ]
