# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_meshrecord_parentmeshid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DODRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DODId', models.CharField(max_length=128)),
                ('Name', models.TextField()),
                ('IsSynonym', models.BooleanField()),
            ],
        ),
    ]
