# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dodrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnotationDocumentId', models.IntegerField()),
                ('AnnotationId', models.IntegerField()),
                ('OntologyName', models.CharField(max_length=128)),
                ('OntologyRecordId', models.IntegerField()),
                ('MatchStrength', models.IntegerField()),
            ],
        ),
    ]
