# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_matchrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrecord',
            name='OntologyName',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='matchrecord',
            name='OntologyRecordId',
            field=models.IntegerField(null=True),
        ),
    ]
