# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170911_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologymatch',
            name='NLPDotProduct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
