# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170718_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark2CureAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentId', models.IntegerField()),
                ('AnnotationId', models.IntegerField()),
                ('AnnotationText', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Mark2CurePassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentId', models.IntegerField()),
                ('PassageId', models.IntegerField()),
                ('PassageText', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mark2cureannotation',
            name='Passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Mark2CurePassage'),
        ),
    ]
