# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170719_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark2cureannotation',
            name='Solved',
            field=models.BooleanField(default=False),
        ),
    ]
