# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ontologymatch_nlpdotproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologymatch',
            name='ConvenienceMatchString',
            field=models.CharField(default='', max_length=256),
        ),
    ]
