# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mark2cureannotation_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecord',
            name='Reason',
            field=models.IntegerField(default=-1),
        ),
    ]
