# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170930_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ontologymatchqualityreason',
            name='QualityConsensus',
        ),
        migrations.AddField(
            model_name='ontologymatchqualityreason',
            name='MatchQuality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OntologyMatchQuality'),
        ),
        migrations.AddField(
            model_name='ontologymatchqualityreason',
            name='Reason',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ontologymatchqualityreason',
            name='SubmittedBy',
            field=models.CharField(default='NOWHEREMAN', max_length=128),
        ),
        migrations.AddField(
            model_name='ontologymatchqualityreason',
            name='SubmittedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
