# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171001_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyMatchQualityConsensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchStrength', models.IntegerField()),
                ('Match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OntologyMatch')),
            ],
        ),
    ]
