# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171001_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologymatchqualityconsensus',
            name='ReasonConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
