# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_ontologymatchqualityconsensus_reasonconfirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ontologymatchqualityconsensusreason',
            name='MatchQuality',
        ),
        migrations.AddField(
            model_name='ontologymatchqualityconsensusreason',
            name='MatchQualityConsensus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OntologyMatchQualityConsensus'),
        ),
    ]
